services:
  api:
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase-admin.json
    volumes:
      - type: bind
        source: ./secrets/firebase-admin.json
        target: /run/secrets/firebase-admin.json
        read_only: true
