{{- if eq .Values.storage.backend "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sport-uploads
  annotations: {helm.sh/resource-policy: keep}
spec:
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: {{ .Values.storage.size }}}}
{{- end }}
